### ISSUE TITLE
Error:  Could not read Ogg bitstream

### ISSUE THREAD

**Issue by Catsy-Boi** [mayo78/vsdave-switch#7]
Every time i load a song, i get an error:

Error:

Could not read Ogg bitstream

Traceback

main.lua:644: in function 'handler'
[C]: at 0x1b2e9c70
[C]: in function 'newSource'
paths.lua:61: in function 'sounds'
states/weeks.lua:482: in function 'enter'
stage.lua:1965: in function 'switch'
lib/gamestate.lua:102: in function 'after'
lib/timer.lua:45: in function 'updateTimerHandle'
lib/timer.lua:64: in function 'update'
main.lua:498: in function 'update'
[C]: in function 'xpcall'

**Comment by mayo78** [comment]
fixed sorry for taking so long to fix this
